In [112]:
# package for multi-label classification

# libraries
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
import arff


In [160]:
# read arff file
# return a dictionary, containing contents of the file.
def read_arff(arff_file, numLabels):
    obj = arff.load(open(arff_file, 'r'))
    data = np.array(obj['data']).astype('float')
    attributes = data[:,0:data.shape[1]-numLabels]
    labels = data[:,data.shape[1]-numLabels:data.shape[1]]
    return {'attributes':attributes,
            'labels':labels,
            'names':obj['attributes']
           }

def NaiveBayes_train(X, y):
    clf = GaussianNB()
    return clf.fit(X, y)

def NaiveBayes_predict(X, model):
    return model.predict(X)


def lead(X, y, method='NaiveBayes'):
    if method == 'NaiveBayes':
        # Step1: train q classifiers using method
        error_array = np.zeros((y.shape))
        for i in range(y.shape[1]):
            y_i = y[:,i]
            model = NaiveBayes_train(X,y_i)
            y_pred = NaiveBayes_predict(X,model)
            error = y_i - y_pred
            error_array[:,i] = error
        
        return error_array
    
        # Step2: use error


In [161]:
# __main__():
file = r'/Users/jiangjunhao/Desktop/ESKDB_HDP/data/small_datasets/emotions/emotions.arff'
data = read_arff(file,6)

X = data['attributes']
y = data['labels']
error_arr = lead(X,y)
#NaiveBayes_train(X,y[:,0])

In [162]:
error_arr.shape

(593, 6)

In [165]:
for i in range(error_arr.shape[0]):
    print(error_arr[i,:])

[ 0.  0.  0. -1. -1.  0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0.  0. -1.  0. -1.  0.]
[ 0.  0.  0.  0. -1.  0.]
[ 0.  0.  0.  0.  0. -1.]
[0. 0. 0. 0. 0. 0.]
[ 0.  1.  0.  0.  0. -1.]
[0. 0. 0. 0. 0. 0.]
[ 0.  1.  0.  0. -1.  0.]
[ 0. -1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0. -1.]
[ 0.  0.  0. -1.  0.  0.]
[ 0.  0. -1.  0.  0.  0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[-1.  0.  1.  0.  0. -1.]
[0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0. -1.  0.  0.  0.  0.]
[-1.  1.  0.  0.  0. -1.]
[-1.  0.  0.  0.  0. -1.]
[0. 0. 0. 0. 0. 0.]
[-1.  0.  0.  0.  0.  0.]
[0. 0. 1. 0. 0. 0.]
[ 0. -1.  0.  0.  0.  0.]
[0. 0. 0. 0. 0. 0.]
[-1.  0.  0.  0.  0. -1.]
[ 0.  0.  0.  0.  0. -1.]
[ 0.  0. -1. -1.  0.  1.]
[-1. -1.  1.  1.  0. -1.]
[ 0. -1.  0.  0.  0.  0.]
[-1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0. -1.]
[ 0.  0.  0. -1. -1.  0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. -1.]
[0. 0. 0. 0. 0. 0.]
[-1.  1.  0.  0.  0. -1.]
[ 0. -1.  0.  0.  1. -1.